### ISSUE TITLE
Move CI to VSTS

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Client.Engineering#23]
- [x] Move Build and Unit Tests on Windows
- [x] Move Functional Tests on windows
- [x] Move Linux unit and functional tests
- [x] Move Mac unit and functional tests
- [x] Move EndToEnd tests on windows

**Comment by rohit21agrawal** [comment]
build of NuGet.Client has successfully been completed to VSTS.

**Comment by rohit21agrawal** [comment]
all test suites have been moved too.
